// All action type names to avoid typos.

export enum ActionTypes {
  LOGIN_BEGIN = "LOGIN_BEGIN",
  LOGIN_ERROR = "LOGIN_ERROR",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  REGISTER_BEGIN = "REGISTER_BEGIN",
  REGISTER_ERROR = "REGISTER_ERROR",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  TOGGLE_PAGE = "TOGGLE_PAGE",
}
